modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="phasmocraftia"
version="1.0.0"
displayName="Phasmocraftia"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="potat, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.phasmocraftia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.phasmocraftia]]
    modId="simple_voicechat_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.phasmocraftia]]
    modId="ldlib_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.phasmocraftia]]
    modId="photon_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

